### ISSUE TITLE
What is the mean of the output in Example 1: Train Keras Regression Model?

### ISSUE THREAD

**Issue by dapratama** [ahmedfgad/KerasGA#2]
Dear Mr. Ahmed F. Gad,

Hallo Dr., I try to learn your pyGAD package starting from your example. But I don't understand with the output of fitness_function in Example 1: Train Keras Regression Model. What is the mean of the output? Because I think the objective of Regression problem is to minimize the output. Why the graph is increased instead of decreased? How to change the graph to show MAE history instead of fitness function?

Thank you

**Comment by ahmedfgad** [comment]
Hello,

In the genetic algorithm, the objective is to increase the fitness values calculated from the fitness function. Thus, the fitness function is a maximization one. This is why the graph is increasing note decreasing.

In the fitness function of the regression example, the mean absolute error is calculated. Because the error function is a minimization function, we have to convert it to a maximization function to be used as the fitness function. This is done according to this line:

```python
solution_fitness = 1.0/abs_error
```

If you want to see plot the graph of the error not the fitness, then simply do the following:
The `best_solutions_fitness` attribute of instances from the `pygad.GA` class holds the best fitness value in each generation. You can convert the fitness values to errors as follows:
```python
best_solutions_error = 1.0 / numpy.array(ga_instance.best_solutions_fitness)
```

Then show the graph:
```python
matplotlib.pyplot.plot(best_solutions_error)
matplotlib.pyplot.show()
```

That should work. Please let me know if you have any doubts.

**Comment by dapratama** [comment]
Great Dr., I have done it. Thank you very much.
